FROM node:lts-alpine

WORKDIR /app
COPY ./package.json ./yarn.lock ./
RUN yarn install
# Install database packages
ARG DATABASE_PACKAGES=sqlite3
RUN yarn add $DATABASE_PACKAGES

COPY . .

CMD yarn dev